apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-react-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-react-app
  template:
    metadata:
      labels:
        app: sample-react-app
    spec:
      containers:
      - image: heroengineer/simple-react-app:latest
        name: sample-react-app
        ports:
        - containerPort: 3000